// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC72RgkymhfHyYugy0ku907HnPkxtho4ZI',
    appId: '1:399231375780:web:26414d668ecfcd9b3fc931',
    messagingSenderId: '399231375780',
    projectId: 'rehabapp-47e0b',
    authDomain: 'rehabapp-47e0b.firebaseapp.com',
    storageBucket: 'rehabapp-47e0b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3DoVOwyCqI7JRUznG_FViJ-SnldHDivU',
    appId: '1:399231375780:android:009ed7805da20ecc3fc931',
    messagingSenderId: '399231375780',
    projectId: 'rehabapp-47e0b',
    storageBucket: 'rehabapp-47e0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIG-ECv-YxktouvEobfDKQLUTIEKInFdU',
    appId: '1:399231375780:ios:998c867d40312abc3fc931',
    messagingSenderId: '399231375780',
    projectId: 'rehabapp-47e0b',
    storageBucket: 'rehabapp-47e0b.firebasestorage.app',
    iosBundleId: 'com.example.rehabAppClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIG-ECv-YxktouvEobfDKQLUTIEKInFdU',
    appId: '1:399231375780:ios:998c867d40312abc3fc931',
    messagingSenderId: '399231375780',
    projectId: 'rehabapp-47e0b',
    storageBucket: 'rehabapp-47e0b.firebasestorage.app',
    iosBundleId: 'com.example.rehabAppClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC72RgkymhfHyYugy0ku907HnPkxtho4ZI',
    appId: '1:399231375780:web:354e9bce336f14a83fc931',
    messagingSenderId: '399231375780',
    projectId: 'rehabapp-47e0b',
    authDomain: 'rehabapp-47e0b.firebaseapp.com',
    storageBucket: 'rehabapp-47e0b.firebasestorage.app',
  );
}
